services:
  postgres:
    image: postgres:latest
    container_name: jobber-postgres
    environment:
      POSTGRES_USER: jobber
      POSTGRES_PASSWORD: jobber
      POSTGRES_DB: jobber
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U jobber']
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    container_name: jobber-auth
    environment:
      - NODE_ENV=development
      - AUTH_APP_VERSION=1.0.0
      - AUTH_DATABASE_URL=postgresql://jobber:jobber@postgres:5432/jobber
      - AUTH_PORT=3000
      - JWT_SECRET=YxD1NH9ox4zu81AoiTEng10kVgPOYIhf
      - JWT_EXPIRATION_MS=2880000
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:3000/healthcheck || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
