// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: jobs.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export interface AcknowledgeJobRequest {
  jobId: number;
}

export interface AcknowledgeJobResponse {
}

export interface JobsServiceClient {
  acknowledge(request: AcknowledgeJobRequest): Observable<AcknowledgeJobResponse>;
}

export interface JobsServiceController {
  acknowledge(
    request: AcknowledgeJobRequest,
  ): Promise<AcknowledgeJobResponse> | Observable<AcknowledgeJobResponse> | AcknowledgeJobResponse;
}

export function JobsServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["acknowledge"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("JobsService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("JobsService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const JOBS_SERVICE_NAME = "JobsService";
