{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: auth-grpc
  labels:
    app: auth
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - port: {{ .Values.auth.port.grpc }}
      targetPort: {{ .Values.auth.port.grpc }}
      protocol: TCP
      name: grpc
{{- end }}