{{- if .Values.products.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: products-grpc
  labels:
    app: products
spec:
  type: ClusterIP
  selector:
    app: products
  ports:
    - port: {{ .Values.products.port.grpc }}
      targetPort: {{ .Values.products.port.grpc }}
      protocol: TCP
      name: grpc
{{- end }}