apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: upload-pvc
spec:
  accessModes:
    {{- if .Values.persistence.ebs }}
    - ReadWriteOnce
    {{- else }}
    - ReadWriteMany
    {{- end }}
  resources:
    requests:
      storage: 1Gi
  {{- if .Values.persistence.ebs }}
  storageClassName: ebs-sc
  {{- end }}