{{- if .Values.jobs.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: jobs-grpc
  labels:
    app: jobs
spec:
  type: ClusterIP
  selector:
    app: jobs
  ports:
    - port: {{ .Values.jobs.port.grpc }}
      targetPort: {{ .Values.jobs.port.grpc }}
      protocol: TCP
      name: grpc
{{- end }}