{{- if .Values.jobs.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: jobs
  labels:
    app: jobs
spec:
  type: ClusterIP
  selector:
    app: jobs
  ports:
    - port: {{ .Values.jobs.port.http }}
      targetPort: {{ .Values.jobs.port.http }}
      protocol: TCP
      name: http
{{- end }}